# site name
siteName: è¯´IT
shortName: è¯´

# Master info. It won't work if the one from (author|authorLink|avatar|authorDesc) be written in post.md
webmaster:
  name: çº ç»“ä¼¦
  avatar: /images/favicon.png
  home: https://shuoit.net
  desc: ä¸€ä¸ªæ¬ğŸ§±çš„åŠ³æ–¯åŸºğŸ˜ï¸ï¸

# CSP Model, true means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
CSP_Enable: false

# favicon
favicon: /images/favicon.png
# unique avatar
avatarShow: false
avatarImage: /images/favicon.png

# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number
homeArticleShown: 10


# your site build time or domain buy time
siteBuildingTime: 01/20/2018


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   æŠ€æœ¯: tech-notes
   äººæ–‡: humanities
   å…¶ä»–: others

# Customize left nav-menus. faName is FontAwesome style name
leftNavMenu:
- uri: help
  title: å¸®åŠ©
  faName: fa-question-circle


# cover info config
coverTitle: ç”¨ä»£ç æ‘‡æ»šè¿™ä¸ªä¸–ç•Œ
coverDescription: ä¸€ä¸ªå…³æ³¨æŠ€æœ¯ä¸äººæ–‡çš„ITåšå®¢

# sns url
sns:
  telegram: http://t.me/kunyintang
  instagram: https://www.instagram.com/mtangsir/
  twitter: https://twitter.com/tangkunyin
  github: https://github.com/tangkunyin

# article declare. default content in languages
postDeclare: true

# Git-pages server info
pageServerName: Coding
pageServerUrl: https://coding.net/register?key=bcace447-fa41-4579-9783-86fdf0f723e2

# Local search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # unescape html strings to the readable one
  unescape: false

## Analytics setting. Google default
analyticsId:


## Comments settings. Disqus | Gitment
disqus_shortname:

#### Gitment: Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: false
  githubID:
  repo:
  ClientID:
  ClientSecret:
  lazy: true

