# site name
site_name: 说IT
short_name: 说

# Master info. It won't work if the one from (author|authorLink|avatar|authorDesc) be written in post.md
webmaster:
  name: 托码思
  avatar: /images/favicon.png
  home: https://about.tangkunyin.com
  desc: 一个写代码的「伪文人」

# CSP Mode, true means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
csp_enable: true

# Read Mode. day or night
read_mode: day

# favicon
favicon: /images/favicon.png
# unique avatar
avatar_show: false
avatar_image: /images/favicon.png

# Home page sort type: -1: newer first，1: older first.
home_page_sort: -1
# Home page article shown number
home_article_shown: 10

# your site build time or domain buy time
site_building_time: 01/20/2018

# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   技术: tech
   人文: huma

# Customize left navigation menus. faName is FontAwesome style name
left_nav_menus:
- uri: help
  title: 帮助
  faName: fa-question-circle


# cover info config
cover_title: 用代码摇滚这个世界
cover_description: 一个关注技术与人文的IT博客

# cover sns info
sns:
  telegram: https://t.me/kunyintang
  twitter: https://twitter.com/tangkunyin
  github: https://github.com/tangkunyin
  stack-overflow: https://stackoverflow.com/users/6133063/tangkunyin
  

# page pop qrcode
donateImg: /images/donate-qr.png
snsQRCode: 

# article declare. default content in languages
post_declare: true

# Local search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # unescape html strings to the readable one
  unescape: false

## Analytics setting. Google default
analytics:
  enable: false
  google_analytics_id:

## Google AdSense.
adsense:
  auto: true
  client_id:  
  page_tb_id:
  archive_id:
  tags_id:
  post_inner_id:
  post_left_id:
  post_right_id:


## Comments settings. Disqus
##                  | Gitment（Introduction: https://imsun.net/posts/gitment-introduction/）
##                  | gitalk  (Official website: https://gitalk.github.io/)
comments:
  enable: false
  disqus_shortname:
  gitalk:
    on: true
    clientID:
    clientSecret:
    owner:
    repo:
    admin: ['your name']
    perPage: 6
    pagerDirection: 'last'
  gitment:
    repo:
    githubID:
    ClientID:
    ClientSecret:
    lazy: true

# Git-pages server info (Coding Pages|Github Pages)
server_name:
server_url:

mathjax:
   enable: false

## Baidu ziyuan auto-commit. see https://ziyuan.baidu.com/
baidu_auto_push: false

## MIIT Info. see https://beian.miit.gov.cn/#/Integrated/index
miit_license: ## 例：京ICP备xxxxx号
